### ISSUE TITLE
Extension signing now mandatory?

### ISSUE THREAD

**Issue by matatk** [matatk/landmarks#10]
Looks like it may be: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by matatk** [comment]
Should consider this, too: https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by kevinmcfaul** [comment]
Just came across the same thing. +1 on any information on this request.

**Comment by matatk** [comment]
Due to this change, I've taken the opportunity to re-write as a WebExtension and will submit that to both the Mozilla Add-on database and automatic signing when the [`convert-to-webextension` branch](https://github.com/matatk/landmarks/tree/convert-to-webextension) is ready.

**Comment by matatk** [comment]
I have at last merged the WebExtension in to master and have submitted the extension for review by Mozilla (and have published it in the Chrome Web Store), so I will close this now.
