### ISSUE TITLE
DPUB-ARIA 1.0 landmarks

### ISSUE THREAD

**Issue by quasicomputational** [matatk/landmarks#148]
[The DPUB-ARIA 1.0 spec](https://www.w3.org/TR/dpub-aria-1.0/) defines a bunch of new roles, some of which are landmarks. I did a pass over them, and found these that are subclasses of `landmark`:
- `doc-acknowledgements`
- `doc-afterword`
- `doc-appendix`
- `doc-bibliography`
- `doc-chapter`
- `doc-conclusion`
- `doc-credits`
- `doc-endnotes`
- `doc-epilogue`
- `doc-errata`
- `doc-foreword`
- `doc-glossary`
- `doc-index` (via `navigation`)
- `doc-introduction`
- `doc-pagelist` (via `navigation`)
- `doc-part`
- `doc-preface`
- `doc-prologue`
- `doc-toc` (via `navigation`)

It'd be nice to be able to support these too. I had a peek at the code and a first pass could just be adding these values to the list in `content.finder.js`, but the raw names are sort of ugly to expose in the UI (prefixes, ew); on the other hand, `contentinfo` already leaks through and that's not exactly pretty either.

**Comment by matatk** [comment]
Great idea, thanks (and for going through all the roles). I agree this would be trivial to add (except for the hierarchical difference between roles that inherit from `landmark` and those that inherit from `navigation`, but I'm not sure that's important right now :-)).

It also sounds like a simple mapping betwixt ARIA role and "user friendly" name may be in order. I had not included this so far as, whilst I agree "contentinfo" is inelegant, I'm not really sure what else to call it, and the ARIA spec *is* the definitive thing here.

However, for the book parts, this would be necessary. I'd definitely need to make them localised, too.

It doesn't seem that any of the DP roles conflict with normal ARIA roles (which makes sense), so they can probably just be added and always supported, regardless of the document type. (Originally I was thinking of having a user preference for enabling them or not, but that seems overly complex now.)

**Comment by quasicomputational** [comment]
Agreed on not over-complicating things. Maybe in the future, but, since `navigation` doesn't currently get handled specially, I don't see what the benefit would be today.

RE `contentinfo`, I was thinking that `content information` would be prettier and, while still jargon, a little bit less obscure.

**Comment by matatk** [comment]
I've almost finished addressing this in the [`digital-publishing-landmarks`](https://github.com/matatk/landmarks/tree/digital-publishing-landmarks) branch. I was wondering if you know of any good example documents containing these roles (that I could use for testing and to give a link to users in the README)? I tried searching the ARIA module's spec, and [the ARIA module's GitHub repo](https://github.com/w3c/dpub-aria) but haven't found anything so far.

**Comment by quasicomputational** [comment]
No, sorry, I don't have any examples from the wild. [Major publishers are apparently already using it](http://w3c.github.io/test-results/dpub-aria/), so that's one option for testing material. It might also be possible to grab any epubs you have lying around and convert the epub:type= to the analogous DPUB-ARIA role= and see if that looks okay.

**Comment by matatk** [comment]
I've implemented this and it's available [to try out](https://github.com/matatk/landmarks#development). Planning to make a new release with this in soon.
