### ISSUE TITLE
Region landmark not recognised with more than a single value in aria-labelledby

### ISSUE THREAD

**Issue by MarcoHengstenberg** [matatk/landmarks#168]
Hello,

first of all I want to thank you for this amazing add-on/extension. Helps me so much in my day-to-day work. ❤️ 

Secondly I think I may have found a bug: when providing more than a single value inside the `aria-labelledby` attribute, the add-on won't recognize the container as a landmark anymore.

Example Markup:

```html
<section aria-labelledby="idValueOne idValueTwo">
    <h2 id="idValueOne">
        Some Text
    </h2>

    <p id="idValueTwo">
        Some Text
    </p>
</section>
```

I read up on the idea itself and it is supposed to work: https://www.w3.org/WAI/GL/wiki/Using_aria-labelledby_to_concatenate_a_label_from_several_text_nodes#Example_1:_A_time-out_input_field_with_concatenated_label I just don't know, whether it should create a landmark by that. So this might prove to be no bug at all.

Cheers! 😃

**Comment by matatk** [comment]
Hi @MarcoHengstenberg, glad you find Landmarks useful; thanks for letting me know :-). Also, thanks for your clear and helpful bug report. I don't think I created any test cases for multiple ID values, so this is almost certainly a bug; I should be able to fix it in the next release.

**Comment by matatk** [comment]
I thought about this more, and realised that I wouldn't actually encourage labelling landmark regions with multiple labels. Whilst it may be necessary in some cases, I think in the vast majority it could indicate that the page's landmark structure or labelling is too complicated.

However, this is something that can happen in the wild (and is permitted by the spec, though I'm pretty sure it's more intended for labelling form controls with multiple pieces of information). Also I do expect there will be some circumstances where it *is* of genuine help, and of course it's a bug that Landmarks doesn't (or rather didn't) support the spec entirely.

I've fixed it now, and will make a new release soon. Thanks again for your feedback.

**Comment by MarcoHengstenberg** [comment]
I agree; in 99 out of 100 times one label suffices the needs of what I'm building. I just ran into one of those edge cases and, yeah, here we are. 😃

Thanks for integrating this! ❤️
