### ISSUE TITLE
Add Support for ARIA-Roledescription

### ISSUE THREAD

**Issue by yatil** [matatk/landmarks#316]
https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription

Thanks for all the work on this Extension!

**Comment by matatk** [comment]
This is a great idea, thanks (and you're welcome). Sorry for the delayed response, it's been a busy month, but I am hoping to get back on to this soon.

**Comment by matatk** [comment]
I've just released version 2.6.0, which includes this feature. Sorry it took a while, and thanks again for the suggestion, @yatil. If you're using the extension, you should receive the update very soon.
