### ISSUE TITLE
Reading all footers as contentinfo

### ISSUE THREAD

**Issue by aardrian** [matatk/landmarks#37]
I make extensive use of the following pattern:

     <blockquote>
        text
        <footer><cite>attribution</cite></footer>
     <blockquote>

When I use the plug-in, every one of those is listed as having the landmark role `contentinfo`. [Example page](http://adrianroselli.com/2015/03/typefaces-for-dyslexia.html)

That pattern was originally informed from [this HTML5 Doctor post](http://html5doctor.com/blockquote-q-cite/), which noted in 2012 that it was non-conforming, but then an [updated post in 2013](http://html5doctor.com/cite-and-blockquote-reloaded/) suggested it was.

Regardless, my understanding was that a `<footer>` gets the `contentinfo` role when the [nearest ancestor sectioning content or sectioning root element](https://www.w3.org/TR/html51/sections.html#the-footer-element) is the `<body>` element. Also that [there should be only one `contentinfo` role](https://www.w3.org/TR/wai-aria/roles#contentinfo).

**Comment by matatk** [comment]
Thank you for this clear and comprehensive issue report.  I will have to take some time to digest the spec a bit (though I expect to come to the same conclusion as you).  It looks like [the checks for whether `<footer>` should be given a role](https://github.com/matatk/landmarks/blob/master/src/static/content.js#L117) need to be updated.

This provides further justification for adding tests to this project&mdash;at the very least a set of example pages and the expected landmark hierarchy.  This is something I've had on the TODO list for some time and now there is more incentive to address it next, now that the conversion to being a WebExtension is complete.

**Comment by stevefaulkner** [comment]
when `footer` [(nearest ancestor sectioning content or sectioning root element is not body, or parent is main)](https://w3c.github.io/html-aam/#el-footer) it does not have a `role=contentinfo`, same goes for `header`. note blockquote is a [sectioning root element](https://w3c.github.io/html/sections.html#sectioning-roots)

**Comment by matatk** [comment]
Thanks for the clarification @stevefaulkner; thus we know for even sur-er now that [the existing checks for whether `<footer>` should be given a role](https://github.com/matatk/landmarks/blob/master/src/static/content.js#L117) need to be expanded (and the question in the code comment there has been answered too; thanks).

I will also be adding to the repo several HTML fragments and expected landmarks and get those included as part of the build/test process.

For my own reference, it looks like I need to implement the ideas of:

 - sectioning content elements;
 - sectioning root elements;
 - `<main>` and `<body>`;
 - nearest ancestor of either {sectioning content} or {sectioning root} type (or `<main>`/`<body>` as backstops).

This should enable the code to read more like the spec.

**Comment by matatk** [comment]
Quick update for you: this has been fixed for a little while in the ["start-tests" branch](https://github.com/matatk/landmarks/tree/start-tests), though I'm going to add some more tests to it, and do a bit of refactoring, before making another release.

**Comment by matatk** [comment]
Thanks again for your help; I believe this is fixed now. I am going to maybe add some more tests before releasing a new version. For now, if you are very curious, have a surfeit of spare time and wanted to try it, you could use the [local testing procedure discussed in the README](https://github.com/matatk/landmarks#development).
