### ISSUE TITLE
trailing/leading spaces in roles cause issues

### ISSUE THREAD

**Issue by jnurthen** [matatk/landmarks#464]
role="main " is not recognized as a landmark.
Trailing and leading spaces should all be allowed as roles are space-separated tokens in HTML https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#space-separated-tokens

Further role="main foo" and role="foo main" (assuming foo isn't a known role in the latter case) should also both resolve to main in the landmarks extension.

**Comment by matatk** [comment]
Great catch; thanks @jnurthen!

**Comment by matatk** [comment]
Quick update, as it's been a while!

I have fixed this on my local machine; just have a few performance tests to run. I'm expecting to complete that over the weekend, and push new versions of both the [test suite](https://github.com/matatk/page-structural-semantics-scanner-tests) and this extension (it'll take a while after that for the extension to be reviewed by the browsers; usually that's not more than a few days).

**Comment by matatk** [comment]
2.11.1 has been released and contains the fix for this bug. It's available in Firefox and Chrome now; Opera and Edge should follow in several days, after review. Thanks again for your report.
