### ISSUE TITLE
Problem with the thickness of the border

### ISSUE THREAD

**Issue by matatk** [matatk/landmarks#479]
Feedback from @kimviens in #477.

The ask is:

> Ability to adjust the size of the border and the label of the landmark independently.

Further info:

> About the border: the problem is not the thickness of the border it is rather that the control for the thickness of the border is the same as for the size of the text. Therefore, if I want large text it will set a large border and therefore cover content. I would like to know if it would be possible to decouple the controls?

The border shouldn't be varying in thickness so I need to investigate this more. Also I did notice during testing once that the size of the text was very small, and the colour was wrong. This was because the extension was getting null values (rather than the defaults) for the text size, but I don't know what caused it. Possibly a bug in the web-ext infrastructure, or my use of it, as haven't seen it since, but I wondered if this was related somehow. The border size still didn't very though.

**Comment by kimviens** [comment]
Thank you for adding this issue @matatk! 

Indeed, when the user wants bigger text to read they find themselves with a huge border. Text size and border size seems to be coupled. Additionally, I am able to put in a negative value for the border size, see image below for an example where I put the border equal to minus 2:
![image](https://user-images.githubusercontent.com/56558696/187514802-f53bf096-4358-4e72-bde6-bff5d62ed2ea.png)

**Comment by kimviens** [comment]
Hi @matatk, it looks like the current version in main has solved this issue. The font size is no longer coupled to the border size. I think this is solved.

I tested in Edge, Chrome and Firefox.

**Comment by matatk** [comment]
Thanks for testing. That's really strange, though, as I don't think I did anything that should've affected it. I mentioned above that I seemed to encounter an edge case in which the options weren't set properly at one point during my testing. I will try a clean install from the various extension stores, and see if I can trigger the behaviour you were getting.

**Comment by matatk** [comment]
When the coupling of border size and label font size happened, was it on *every* page (including the extension's own options page)? Would you be able to post the URL of a page that always had the problem?

I'm still not able to reproduce the border thickness being coupled to the font size in the latest version available from the Firefox/Chrome extensions sites (2.11.1). However, using that version, I did find some problems. As they're not related to the thickness of the border I filed them separately as #484.

I still need to check out what's different between 2.11.1 and `main` at the time you reported the issue (35aeebe).

**Comment by kimviens** [comment]
Hi @matatk, sorry for the late reply, I got hit by Covid. 

I agree, the findings were that in the testing I did, the coupling did NOT occur. I just downloaded and tested the landmark extension again and did not find the issue either.

I think we could say this is resolved? If the issue reappear we could reopen this issue.

**Comment by matatk** [comment]
I hope you are feeling better now, or very soon, @kimviens!

Thank you for re-testing. It seems like this was triggered by something very edge-case-y and, as you say, is not currently a problem. I'll leave this open to remind me to add code to stop the preference value being set to `null`, but will close it when that's fixed. Please do re-open it after that point if the problem comes back.

**Comment by matatk** [comment]
It wasn't quite that the label size was being set to `null` (all the settings are stored as strings; it was being set to the empty string when the input was blanked out by the user), but that has now been fixed, as per #486, so I think this will be fixed now too. Feel free to re-open if not, of course.
